apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: jschless-test
  generateName: cord-19
  labels:
    app: process-cord-19
spec:
  serviceAccountName: argo-workflow
  entrypoint: entrypoint
  volumeClaimTemplates:
    - metadata:
        name: data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

  templates:
    - name: entrypoint
      steps:
        - - name: cord-19-acquisition
            template: data-acquisition
        - - name: cord-19-processing
            template: data-processing
    - name: data-acquisition
      container:
        name: data-acquisition
        image: image-registry.openshift-image-registry.svc:5000/jschless-test/cord-19-nlp-acq
        command: []
        volumeMounts:
          - name: data-storage
            mountPath: /mnt/data
    - name: data-processing
      container: 
        name: data-processing
        image: image-registry.openshift-image-registry.svc:5000/jschless-test/cord-19-nlp-proc
        command: []
        volumeMounts:
          - name: data-storage
            mountPath: /mnt/data

